--------------------------------------------------------------------------------
-- Exam Halls & Proctoring Allocation Management System
-- 01_schema.sql  —  Tables, constraints, indexes, soft-delete views
-- Target: Oracle 19c / 21c / 23ai   (run as the application schema owner)
--------------------------------------------------------------------------------
-- Conventions
--   * PKs are IDENTITY columns (GENERATED BY DEFAULT ON NULL) so seed scripts and
--     the Java layer can omit them; RETURNING ... INTO gives the new id back.
--   * All flag columns are CHAR(1) 'Y'/'N' with CHECK constraints.
--   * All constraints are named so ORA- errors are readable in the UI
--     (e.g. ORA-00001: unique constraint (EXAM_ADMIN.UK_ROOMS_CODE) violated).
--   * Soft-delete tables (USERS, TEACHERS, ROOMS) carry two extra audit columns
--     UPDATED_AT / DELETED_AT, maintained by triggers in 02_triggers.sql.
--   * EXAM_PERIODS.START_TIME / END_TIME are DATEs of which ONLY the time-of-day
--     is meaningful. The real slot is EXAM_DATE + (START_TIME - TRUNC(START_TIME)).
--------------------------------------------------------------------------------

SET DEFINE OFF

-- ============================================================================
-- 1. ROLES
-- ============================================================================
CREATE TABLE roles (
    role_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    role_name         VARCHAR2(50)  NOT NULL,
    role_description  VARCHAR2(200),
    CONSTRAINT pk_roles       PRIMARY KEY (role_id),
    CONSTRAINT uk_roles_name  UNIQUE (role_name)
);

-- ============================================================================
-- 2. USERS
-- ============================================================================
CREATE TABLE users (
    user_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    username       VARCHAR2(50)  NOT NULL,
    password_hash  VARCHAR2(256) NOT NULL,
    full_name      VARCHAR2(150) NOT NULL,
    role_id        NUMBER        NOT NULL,
    teacher_id     NUMBER,                               -- links TEACHER / COMMITTEE_HEAD logins to their teacher record
    created_at     DATE          DEFAULT SYSDATE NOT NULL,
    is_deleted     CHAR(1)       DEFAULT 'N' NOT NULL,
    updated_at     DATE,
    deleted_at     DATE,
    CONSTRAINT pk_users           PRIMARY KEY (user_id),
    CONSTRAINT uk_users_username  UNIQUE (username),
    CONSTRAINT fk_users_role      FOREIGN KEY (role_id) REFERENCES roles (role_id),
    CONSTRAINT uk_users_teacher   UNIQUE (teacher_id),         -- one login per teacher (NULLs allowed)
    CONSTRAINT ck_users_deleted   CHECK (is_deleted IN ('Y', 'N')),
    -- BCrypt hashes are 60 chars and start with $2a$/$2b$/$2y$
    CONSTRAINT ck_users_pwd_hash  CHECK (password_hash LIKE '$2_$%' AND LENGTH(password_hash) >= 59)
);

-- ============================================================================
-- 3. DEPARTMENTS
-- ============================================================================
CREATE TABLE departments (
    dept_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    dept_name  VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_departments       PRIMARY KEY (dept_id),
    CONSTRAINT uk_departments_name  UNIQUE (dept_name)
);

-- ============================================================================
-- 4. TEACHERS
-- ============================================================================
CREATE TABLE teachers (
    teacher_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    full_name        VARCHAR2(150) NOT NULL,
    teacher_code     VARCHAR2(30)  NOT NULL,
    dept_id          NUMBER        NOT NULL,
    max_daily_load   NUMBER(2)     DEFAULT 2  NOT NULL,   -- max supervision sessions per day
    max_weekly_load  NUMBER(3)     DEFAULT 8  NOT NULL,   -- max supervision sessions per ISO week
    hours_balance    NUMBER(6,2)   DEFAULT 0  NOT NULL,   -- accumulated supervision hours (fairness)
    is_deleted       CHAR(1)       DEFAULT 'N' NOT NULL,
    updated_at       DATE,
    deleted_at       DATE,
    CONSTRAINT pk_teachers         PRIMARY KEY (teacher_id),
    CONSTRAINT uk_teachers_code    UNIQUE (teacher_code),
    CONSTRAINT fk_teachers_dept    FOREIGN KEY (dept_id) REFERENCES departments (dept_id),
    CONSTRAINT ck_teachers_daily   CHECK (max_daily_load BETWEEN 0 AND 10),
    CONSTRAINT ck_teachers_weekly  CHECK (max_weekly_load >= max_daily_load),
    CONSTRAINT ck_teachers_hours   CHECK (hours_balance >= 0),
    CONSTRAINT ck_teachers_deleted CHECK (is_deleted IN ('Y', 'N'))
);

CREATE INDEX ix_teachers_dept ON teachers (dept_id);

-- USERS is created before TEACHERS, so its FK to TEACHERS is added here.
ALTER TABLE users ADD CONSTRAINT fk_users_teacher FOREIGN KEY (teacher_id) REFERENCES teachers (teacher_id);

-- ============================================================================
-- 5. COURSES
-- ============================================================================
CREATE TABLE courses (
    course_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    course_name  VARCHAR2(100) NOT NULL,
    course_code  VARCHAR2(20)  NOT NULL,
    dept_id      NUMBER        NOT NULL,
    grade_level  VARCHAR2(30)  NOT NULL,
    CONSTRAINT pk_courses       PRIMARY KEY (course_id),
    CONSTRAINT uk_courses_code  UNIQUE (course_code),
    CONSTRAINT fk_courses_dept  FOREIGN KEY (dept_id) REFERENCES departments (dept_id)
);

CREATE INDEX ix_courses_dept ON courses (dept_id);

-- ============================================================================
-- 6. ROOMS
-- ============================================================================
CREATE TABLE rooms (
    room_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    room_code         VARCHAR2(20)  NOT NULL,
    building          VARCHAR2(50)  NOT NULL,
    regular_capacity  NUMBER(4)     NOT NULL,
    exam_capacity     NUMBER(4)     NOT NULL,
    room_status       VARCHAR2(20)  DEFAULT 'AVAILABLE' NOT NULL,
    is_deleted        CHAR(1)       DEFAULT 'N' NOT NULL,
    updated_at        DATE,
    deleted_at        DATE,
    CONSTRAINT pk_rooms           PRIMARY KEY (room_id),
    CONSTRAINT uk_rooms_code      UNIQUE (room_code),
    CONSTRAINT ck_rooms_reg_cap   CHECK (regular_capacity > 0),
    CONSTRAINT ck_rooms_exam_cap  CHECK (exam_capacity > 0 AND exam_capacity <= regular_capacity),
    CONSTRAINT ck_rooms_status    CHECK (room_status IN ('AVAILABLE', 'MAINTENANCE', 'UNAVAILABLE')),
    CONSTRAINT ck_rooms_deleted   CHECK (is_deleted IN ('Y', 'N'))
);

-- ============================================================================
-- 7. EXAM_PERIODS   (time-of-day templates: 'First Period' 09:00-11:00 ...)
-- ============================================================================
CREATE TABLE exam_periods (
    period_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    period_name  VARCHAR2(30) NOT NULL,
    start_time   DATE         NOT NULL,
    end_time     DATE         NOT NULL,
    CONSTRAINT pk_exam_periods       PRIMARY KEY (period_id),
    CONSTRAINT uk_exam_periods_name  UNIQUE (period_name),
    CONSTRAINT ck_exam_periods_range CHECK (end_time > start_time),
    CONSTRAINT ck_exam_periods_day   CHECK (TRUNC(start_time) = TRUNC(end_time))
);

-- ============================================================================
-- 8. EXAM_SCHEDULE
-- ============================================================================
CREATE TABLE exam_schedule (
    exam_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    exam_date  DATE          NOT NULL,
    course_id  NUMBER        NOT NULL,
    period_id  NUMBER        NOT NULL,
    notes      VARCHAR2(300),
    CONSTRAINT pk_exam_schedule         PRIMARY KEY (exam_id),
    CONSTRAINT fk_exam_schedule_course  FOREIGN KEY (course_id) REFERENCES courses (course_id),
    CONSTRAINT fk_exam_schedule_period  FOREIGN KEY (period_id) REFERENCES exam_periods (period_id),
    CONSTRAINT uk_exam_schedule_course  UNIQUE (course_id, exam_date),
    CONSTRAINT ck_exam_schedule_date    CHECK (exam_date = TRUNC(exam_date))
);

CREATE INDEX ix_exam_schedule_slot   ON exam_schedule (exam_date, period_id);
CREATE INDEX ix_exam_schedule_period ON exam_schedule (period_id);

-- ============================================================================
-- 9. STUDENTS
-- ============================================================================
CREATE TABLE students (
    student_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    student_code       VARCHAR2(30)  NOT NULL,
    full_name          VARCHAR2(150) NOT NULL,
    grade_level        VARCHAR2(30)  NOT NULL,
    section            VARCHAR2(10),                     -- class section within the grade (A, B ...)
    has_special_needs  CHAR(1)       DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_students          PRIMARY KEY (student_id),
    CONSTRAINT uk_students_code     UNIQUE (student_code),
    CONSTRAINT ck_students_special  CHECK (has_special_needs IN ('Y', 'N'))
);

CREATE INDEX ix_students_grade ON students (grade_level);

-- ============================================================================
-- 10. SEATING_ALLOCATION
-- ============================================================================
CREATE TABLE seating_allocation (
    seating_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    exam_id            NUMBER       NOT NULL,
    room_id            NUMBER       NOT NULL,
    student_id         NUMBER       NOT NULL,
    seat_number        VARCHAR2(10) NOT NULL,
    attendance_status  VARCHAR2(15) DEFAULT 'ABSENT_PENDING' NOT NULL,
    CONSTRAINT pk_seating_allocation   PRIMARY KEY (seating_id),
    CONSTRAINT fk_seating_exam         FOREIGN KEY (exam_id)    REFERENCES exam_schedule (exam_id) ON DELETE CASCADE,
    CONSTRAINT fk_seating_room         FOREIGN KEY (room_id)    REFERENCES rooms (room_id),
    CONSTRAINT fk_seating_student      FOREIGN KEY (student_id) REFERENCES students (student_id),
    CONSTRAINT uk_seating_exam_student UNIQUE (exam_id, student_id),
    CONSTRAINT uk_seating_exam_seat    UNIQUE (exam_id, room_id, seat_number),
    CONSTRAINT ck_seating_attendance   CHECK (attendance_status IN ('ABSENT_PENDING', 'PRESENT', 'ABSENT', 'EXCUSED'))
);

CREATE INDEX ix_seating_room    ON seating_allocation (room_id, exam_id);
CREATE INDEX ix_seating_student ON seating_allocation (student_id);

-- ============================================================================
-- 11. SUPERVISION_ROSTER
-- ============================================================================
-- ASSIGNMENT_STATUS lifecycle:  CONFIRMED -> REPLACED (substituted, see SUPERVISION_AUDIT)
--                               CONFIRMED -> CANCELLED (manually removed)
CREATE TABLE supervision_roster (
    roster_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    exam_id            NUMBER       NOT NULL,
    room_id            NUMBER       NOT NULL,
    teacher_id         NUMBER       NOT NULL,
    role_type          VARCHAR2(20) NOT NULL,
    assignment_status  VARCHAR2(20) DEFAULT 'CONFIRMED' NOT NULL,
    CONSTRAINT pk_supervision_roster PRIMARY KEY (roster_id),
    CONSTRAINT fk_roster_exam        FOREIGN KEY (exam_id)    REFERENCES exam_schedule (exam_id),
    CONSTRAINT fk_roster_room        FOREIGN KEY (room_id)    REFERENCES rooms (room_id),
    CONSTRAINT fk_roster_teacher     FOREIGN KEY (teacher_id) REFERENCES teachers (teacher_id),
    CONSTRAINT ck_roster_role        CHECK (role_type IN ('HEAD_OF_COMMITTEE', 'PROCTOR')),
    CONSTRAINT ck_roster_status      CHECK (assignment_status IN ('CONFIRMED', 'REPLACED', 'CANCELLED'))
);

CREATE INDEX ix_roster_exam_room ON supervision_roster (exam_id, room_id);
CREATE INDEX ix_roster_teacher   ON supervision_roster (teacher_id, assignment_status);
CREATE INDEX ix_roster_room      ON supervision_roster (room_id);

-- A teacher can hold only one ACTIVE assignment per exam (history rows are ignored).
CREATE UNIQUE INDEX ux_roster_active_teacher ON supervision_roster (
    CASE WHEN assignment_status = 'CONFIRMED' THEN exam_id    END,
    CASE WHEN assignment_status = 'CONFIRMED' THEN teacher_id END
);

-- Exactly one ACTIVE head of committee per exam + room.
CREATE UNIQUE INDEX ux_roster_active_head ON supervision_roster (
    CASE WHEN assignment_status = 'CONFIRMED' AND role_type = 'HEAD_OF_COMMITTEE' THEN exam_id END,
    CASE WHEN assignment_status = 'CONFIRMED' AND role_type = 'HEAD_OF_COMMITTEE' THEN room_id END
);

-- ============================================================================
-- 12. SUPERVISION_AUDIT   (immutable log of substitutions)
-- ============================================================================
-- ROSTER_ID points at the ORIGINAL (now 'REPLACED') roster row, so the replaced
-- teacher is always recoverable via SUPERVISION_ROSTER.TEACHER_ID.
CREATE TABLE supervision_audit (
    audit_id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    roster_id              NUMBER        NOT NULL,
    substitute_teacher_id  NUMBER        NOT NULL,
    executed_by            NUMBER        NOT NULL,
    reason                 VARCHAR2(300) NOT NULL,
    audit_timestamp        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_supervision_audit   PRIMARY KEY (audit_id),
    CONSTRAINT fk_audit_roster        FOREIGN KEY (roster_id)             REFERENCES supervision_roster (roster_id),
    CONSTRAINT fk_audit_substitute    FOREIGN KEY (substitute_teacher_id) REFERENCES teachers (teacher_id),
    CONSTRAINT fk_audit_executed_by   FOREIGN KEY (executed_by)           REFERENCES users (user_id)
);

CREATE INDEX ix_audit_roster      ON supervision_audit (roster_id);
CREATE INDEX ix_audit_substitute  ON supervision_audit (substitute_teacher_id);
CREATE INDEX ix_audit_executed_by ON supervision_audit (executed_by);

-- ============================================================================
-- 13. TEACHER_STUDENT_RELATIONS   (kinship up to the 4th degree => conflict of interest)
-- ============================================================================
CREATE TABLE teacher_student_relations (
    relation_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    teacher_id       NUMBER       NOT NULL,
    student_id       NUMBER       NOT NULL,
    relation_degree  NUMBER(1)    NOT NULL,
    notes            VARCHAR2(200),
    CONSTRAINT pk_teacher_student_rel  PRIMARY KEY (relation_id),
    CONSTRAINT fk_tsr_teacher          FOREIGN KEY (teacher_id) REFERENCES teachers (teacher_id),
    CONSTRAINT fk_tsr_student          FOREIGN KEY (student_id) REFERENCES students (student_id) ON DELETE CASCADE,
    CONSTRAINT uk_tsr_pair             UNIQUE (teacher_id, student_id),
    CONSTRAINT ck_tsr_degree           CHECK (relation_degree BETWEEN 1 AND 4)
);

CREATE INDEX ix_tsr_student ON teacher_student_relations (student_id);

-- ============================================================================
-- Active-record views (soft-delete aware)
-- The Java DAOs should SELECT / DELETE through these views. A DELETE on a view is
-- turned into a soft delete by the INSTEAD OF triggers in 02_triggers.sql.
-- ============================================================================
CREATE OR REPLACE VIEW v_users AS
    SELECT user_id, username, password_hash, full_name, role_id, teacher_id, created_at, updated_at
    FROM   users
    WHERE  is_deleted = 'N';

CREATE OR REPLACE VIEW v_teachers AS
    SELECT teacher_id, full_name, teacher_code, dept_id, max_daily_load,
           max_weekly_load, hours_balance, updated_at
    FROM   teachers
    WHERE  is_deleted = 'N';

CREATE OR REPLACE VIEW v_rooms AS
    SELECT room_id, room_code, building, regular_capacity, exam_capacity,
           room_status, updated_at
    FROM   rooms
    WHERE  is_deleted = 'N';

-- Convenience view: every exam with its real start/end timestamps and duration.
CREATE OR REPLACE VIEW v_exam_slots AS
    SELECT e.exam_id,
           e.exam_date,
           e.course_id,
           c.course_code,
           c.course_name,
           c.dept_id                                             AS course_dept_id,
           c.grade_level,
           e.period_id,
           p.period_name,
           e.exam_date + (p.start_time - TRUNC(p.start_time))    AS slot_start,
           e.exam_date + (p.end_time   - TRUNC(p.end_time))      AS slot_end,
           ROUND((p.end_time - p.start_time) * 24, 2)            AS duration_hours
    FROM   exam_schedule e
           JOIN courses      c ON c.course_id = e.course_id
           JOIN exam_periods p ON p.period_id = e.period_id;

-- Convenience view: the active roster with names, for the UI grid and reports.
CREATE OR REPLACE VIEW v_supervision_roster AS
    SELECT r.roster_id, r.exam_id, s.exam_date, s.period_name, s.course_code, s.course_name,
           r.room_id, rm.room_code, rm.building,
           r.teacher_id, t.teacher_code, t.full_name AS teacher_name,
           r.role_type, r.assignment_status
    FROM   supervision_roster r
           JOIN v_exam_slots s ON s.exam_id   = r.exam_id
           JOIN rooms       rm ON rm.room_id  = r.room_id
           JOIN teachers     t ON t.teacher_id = r.teacher_id
    WHERE  r.assignment_status = 'CONFIRMED';
